#!/usr/bin/env bash
# Download CMiO (Critical Minerals in Ores) rock geochemistry release to datasets/cmio/raw/.
# Source: USGS ScienceBase, DOI 10.5066/P14WGQ8V
#   Tharalson, E.R., Graham, G.E., Emsbo, P., and Magnin, B.P., 2025.
#   "Domestic and international rock geochemistry of ore and host rocks
#    generated by the Critical Minerals Mapping Initiative."
#   ScienceBase item 686ecb93d4be020e5c0a6c07 (published 2025-09-16).
#
# Total payload ~1.7 MB — tiny, no archives to extract.

set -u
cd "$(dirname "$0")/../datasets/cmio/raw" || exit 1

declare -A FILES=(
  ["250827_CMMI_Rock_Geochemistry_Data.csv"]="https://www.sciencebase.gov/catalog/file/get/686ecb93d4be020e5c0a6c07?f=__disk__ac%2F23%2F93%2Fac2393c974e1bf194e9538ddcbd1d84c16e5d99b"
  ["250827_CMMI_Rock_Geochemistry_DataDictionary.csv"]="https://www.sciencebase.gov/catalog/file/get/686ecb93d4be020e5c0a6c07?f=__disk__f5%2Fd6%2F85%2Ff5d685e517dd9fd22c1225dae1cd3174561675bb"
  ["250827_CMMI_Rock_Geochemistry_Metadata.xml"]="https://www.sciencebase.gov/catalog/file/get/686ecb93d4be020e5c0a6c07?f=__disk__8d%2F77%2F41%2F8d7741c4978cb02bf967d62067d1865ccb1c0043"
  ["250827_CMMI_Rock_Geochemistry_Locations.png"]="https://www.sciencebase.gov/catalog/file/get/686ecb93d4be020e5c0a6c07?f=__disk__d5%2F26%2Fe5%2Fd526e5dfb81c5f58df0e4d781c84d1ccf3609787"
)

for name in "${!FILES[@]}"; do
  url="${FILES[$name]}"
  echo "=== $name ==="
  curl -fL -C - --retry 5 --retry-delay 5 --retry-all-errors -A "Mozilla/5.0" -o "$name" "$url" \
    && echo "DONE $name ($(wc -c < "$name") bytes)" \
    || echo "FAIL $name"
done

echo
echo "=== Summary ==="
ls -lh . 2>/dev/null || echo "nothing present"
