"""
CMiO (Critical Minerals in Ores) inspection script.

Dataset: USGS — Tharalson et al., 2025.
  "Domestic and international rock geochemistry of ore and host rocks
   generated by the Critical Minerals Mapping Initiative."
  DOI: 10.5066/P14WGQ8V
  ScienceBase item: 686ecb93d4be020e5c0a6c07 (published 2025-09-16)
  Companion publication: Case et al., USGS Fact Sheet 2025-3002
                         DOI: 10.3133/fs20253002

Input files (in datasets/cmio/raw/):
  - 250827_CMMI_Rock_Geochemistry_Data.csv          (~915 KB; samples x columns)
  - 250827_CMMI_Rock_Geochemistry_DataDictionary.csv (~136 KB; column schema)
  - 250827_CMMI_Rock_Geochemistry_Metadata.xml       FGDC metadata
  - 250827_CMMI_Rock_Geochemistry_Locations.png      publisher-supplied map

Structure of Data.csv:
  1,295 rows x 307 columns. 16 metadata columns, then 291 analytical columns.
  Analytical column naming: <Element>_<unit>_<method>
    e.g. Ag_ppm_ICP30, Au_ppb_FA, Zn_ppm_oICP61, SiO2_pct_WDXRF.
  Detection-limit convention: values below the LDL are encoded as a NEGATIVE
  number equal to -LDL. Upper-detection overflows encoded as X.1111 sentinels.
  Null / blank means "not analyzed".

Outputs (in datasets/cmio/outputs/):
  - README.md                              full inspection summary
  - deposit_environment_counts.png         bar chart
  - deposit_group_counts.png               bar chart
  - deposit_type_top.png                   top-20 deposit types
  - country_counts.png                     top-15 country histogram
  - rock_type_counts.png                   rock type bar chart
  - method_coverage.png                    per-column non-null % (sorted)
  - element_coverage_heatmap.png           element x deposit-environment heatmap
  - element_distributions.png              log-scale histograms of 6 ore metals
  - detection_limit_shares.png             % LDL vs detected per key element
  - geographic_scatter.png                 lat/lon colored by Deposit_Environment
"""
from __future__ import annotations

from pathlib import Path
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / 'datasets' / 'cmio' / 'raw'
OUT = ROOT / 'datasets' / 'cmio' / 'outputs'
OUT.mkdir(exist_ok=True, parents=True)

DATA_CSV = RAW / '250827_CMMI_Rock_Geochemistry_Data.csv'
DICT_CSV = RAW / '250827_CMMI_Rock_Geochemistry_DataDictionary.csv'

META_COLS = [
    'Field_ID', 'Sample_Comment', 'Deposit_Environment', 'Deposit_Group',
    'Deposit_Type', 'Latitude_decimal', 'Longitude_decimal', 'Datum',
    'Country', 'State_Province', 'Location_Description', 'Date_Collected',
    'Sample_Source', 'Depth', 'Rock_Type', 'MRP', 'Lab_ID',
]

KEY_ELEMENTS = ['Au', 'Ag', 'Cu', 'Pb', 'Zn', 'Mo']
COL_PATTERN = re.compile(r'^(?P<elem>[A-Za-z0-9]+)_(?P<unit>ppm|ppb|pct)_(?P<method>.+)$')


# ── Column parsing ────────────────────────────────────────────────────────
def analytical_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Return a DataFrame describing each analytical column: element/unit/method."""
    rows = []
    for c in df.columns:
        if c in META_COLS:
            continue
        m = COL_PATTERN.match(c)
        if not m:
            rows.append({'column': c, 'element': None, 'unit': None, 'method': None})
            continue
        rows.append({
            'column': c,
            'element': m.group('elem'),
            'unit': m.group('unit'),
            'method': m.group('method'),
        })
    return pd.DataFrame(rows)


# ── Plots ─────────────────────────────────────────────────────────────────
def bar_counts(counts: pd.Series, title: str, out_png: Path, *, rotation: int = 30,
               figsize=(10, 5), color: str = 'steelblue') -> None:
    fig, ax = plt.subplots(figsize=figsize)
    counts.plot.bar(ax=ax, color=color, edgecolor='black', linewidth=0.3)
    ax.set_title(title)
    ax.set_ylabel('samples')
    ax.grid(axis='y', alpha=0.3)
    for i, v in enumerate(counts.values):
        ax.text(i, v, f'{v:,}', ha='center', va='bottom', fontsize=8)
    plt.setp(ax.get_xticklabels(), rotation=rotation, ha='right')
    plt.tight_layout()
    fig.savefig(out_png, dpi=160)
    plt.close(fig)


def plot_method_coverage(df: pd.DataFrame, acols: pd.DataFrame, out_png: Path) -> None:
    non_null = df[acols['column']].notna().mean().sort_values(ascending=False) * 100
    fig, ax = plt.subplots(figsize=(11, 5))
    ax.plot(np.arange(len(non_null)), non_null.values, color='darkorange', linewidth=1.5)
    ax.fill_between(np.arange(len(non_null)), 0, non_null.values, color='darkorange', alpha=0.25)
    ax.set_title(f'Per-column coverage (non-null %) across {len(non_null)} analytical columns')
    ax.set_xlabel('column rank (high coverage → low)')
    ax.set_ylabel('% non-null')
    ax.grid(alpha=0.3)
    ax.axhline(50, color='gray', linestyle='--', linewidth=0.7)
    ax.text(len(non_null) * 0.98, 51, '50%', ha='right', color='gray', fontsize=8)
    plt.tight_layout()
    fig.savefig(out_png, dpi=160)
    plt.close(fig)


def plot_element_coverage_heatmap(df: pd.DataFrame, acols: pd.DataFrame, out_png: Path) -> None:
    """Element × Deposit_Environment: % of env samples with at least one measurement."""
    elements = sorted(acols.loc[acols['element'].notna(), 'element'].unique())
    envs = sorted(df['Deposit_Environment'].dropna().unique())

    mat = np.full((len(elements), len(envs)), np.nan, dtype=np.float32)
    env_sizes = []
    for j, env in enumerate(envs):
        sub = df[df['Deposit_Environment'] == env]
        env_sizes.append(len(sub))
        for i, el in enumerate(elements):
            cols = acols.loc[acols['element'] == el, 'column'].tolist()
            if not cols:
                continue
            any_val = sub[cols].notna().any(axis=1)
            mat[i, j] = 100.0 * any_val.mean() if len(sub) else np.nan

    fig, ax = plt.subplots(figsize=(10, max(8, len(elements) * 0.18)))
    im = ax.imshow(mat, aspect='auto', cmap='viridis', vmin=0, vmax=100)
    ax.set_xticks(range(len(envs)))
    ax.set_xticklabels([f'{e}\n(n={s})' for e, s in zip(envs, env_sizes)],
                       rotation=25, ha='right', fontsize=8)
    ax.set_yticks(range(len(elements)))
    ax.set_yticklabels(elements, fontsize=7)
    ax.set_title('Element coverage (% of deposit-environment samples with any measurement)')
    cb = plt.colorbar(im, ax=ax, shrink=0.7)
    cb.set_label('% covered')
    plt.tight_layout()
    fig.savefig(out_png, dpi=160)
    plt.close(fig)


def best_method_col(acols: pd.DataFrame, df: pd.DataFrame, element: str) -> str | None:
    """Pick the method column with the most non-null values for a given element."""
    candidates = acols.loc[acols['element'] == element, 'column'].tolist()
    if not candidates:
        return None
    counts = df[candidates].notna().sum()
    return counts.idxmax() if counts.max() > 0 else None


def plot_element_distributions(df: pd.DataFrame, acols: pd.DataFrame, out_png: Path) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(13, 7.5))
    for ax, el in zip(axes.flat, KEY_ELEMENTS):
        col = best_method_col(acols, df, el)
        if col is None:
            ax.set_axis_off()
            continue
        vals = pd.to_numeric(df[col], errors='coerce').dropna()
        pos = vals[vals > 0]
        n_ldl = (vals <= 0).sum()
        if len(pos) == 0:
            ax.set_axis_off()
            continue
        bins = np.logspace(np.log10(pos.min()), np.log10(pos.max()), 40)
        ax.hist(pos, bins=bins, color='steelblue', edgecolor='black', linewidth=0.3)
        ax.set_xscale('log')
        ax.set_title(f'{el} — `{col}`')
        ax.set_xlabel('concentration (log scale)')
        ax.set_ylabel('samples')
        ax.grid(alpha=0.3)
        ax.text(0.02, 0.95,
                f'n positive: {len(pos):,}\nn <LDL: {n_ldl:,}\nmedian: {pos.median():.3g}',
                transform=ax.transAxes, fontsize=8, va='top',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
    fig.suptitle('Distributions for 6 key ore metals (best-covered method per element)', y=1.02)
    plt.tight_layout()
    fig.savefig(out_png, dpi=160, bbox_inches='tight')
    plt.close(fig)


def plot_detection_limit_shares(df: pd.DataFrame, acols: pd.DataFrame, out_png: Path) -> None:
    """For each key element, show % of non-null rows that are below detection (-LDL) vs detected."""
    rows = []
    for el in KEY_ELEMENTS:
        col = best_method_col(acols, df, el)
        if col is None:
            continue
        vals = pd.to_numeric(df[col], errors='coerce').dropna()
        total = len(vals)
        below = (vals <= 0).sum()
        detected = total - below
        rows.append({'element': el, 'column': col, 'detected': detected,
                     'below_ldl': below, 'total': total})
    if not rows:
        return
    r = pd.DataFrame(rows)

    fig, ax = plt.subplots(figsize=(9, 4.5))
    x = np.arange(len(r))
    ax.bar(x, r['detected'], color='seagreen', label='detected (> 0)', edgecolor='black', linewidth=0.3)
    ax.bar(x, r['below_ldl'], bottom=r['detected'], color='lightcoral',
           label='below LDL (≤ 0)', edgecolor='black', linewidth=0.3)
    for i, row in r.iterrows():
        pct = 100.0 * row['detected'] / row['total'] if row['total'] else 0.0
        ax.text(i, row['total'], f'{pct:.0f}% det\nn={row["total"]:,}',
                ha='center', va='bottom', fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels([f'{r.element[i]}\n{r.column[i]}' for i in range(len(r))], fontsize=7)
    ax.set_ylabel('analyzed samples')
    ax.set_title('Detection vs below-LDL counts for key ore metals')
    ax.legend(loc='upper right')
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    fig.savefig(out_png, dpi=160)
    plt.close(fig)


def plot_geographic_scatter(df: pd.DataFrame, out_png: Path) -> None:
    sub = df.dropna(subset=['Latitude_decimal', 'Longitude_decimal']).copy()
    if sub.empty:
        return
    envs = sorted(sub['Deposit_Environment'].dropna().unique())
    cmap = plt.get_cmap('tab10')
    colors = {e: cmap(i % 10) for i, e in enumerate(envs)}

    fig, ax = plt.subplots(figsize=(12, 6.5))
    for env in envs:
        s = sub[sub['Deposit_Environment'] == env]
        ax.scatter(s['Longitude_decimal'], s['Latitude_decimal'],
                   s=14, alpha=0.7, color=colors[env], edgecolor='black', linewidth=0.2,
                   label=f'{env} (n={len(s)})')
    ax.set_xlim(-180, 180)
    ax.set_ylim(-90, 90)
    ax.set_xlabel('Longitude')
    ax.set_ylabel('Latitude')
    ax.set_title(f'CMiO sample locations (n={len(sub):,} with coords) by deposit environment')
    ax.grid(alpha=0.3)
    ax.legend(loc='lower left', fontsize=8, framealpha=0.9)
    plt.tight_layout()
    fig.savefig(out_png, dpi=160)
    plt.close(fig)


# ── README ────────────────────────────────────────────────────────────────
def write_readme(df: pd.DataFrame, acols: pd.DataFrame, out: Path) -> None:
    envs = df['Deposit_Environment'].value_counts(dropna=False)
    groups = df['Deposit_Group'].value_counts(dropna=False)
    types = df['Deposit_Type'].value_counts(dropna=False)
    countries = df['Country'].value_counts(dropna=False)
    rocks = df['Rock_Type'].value_counts(dropna=False)

    n_analytical_total = len(acols)
    n_analytical_parsed = int((acols['element'].notna()).sum())
    unparsed = acols.loc[acols['element'].isna(), 'column'].tolist()
    unique_elements = sorted(acols.loc[acols['element'].notna(), 'element'].unique())
    methods = sorted(acols.loc[acols['method'].notna(), 'method'].unique())
    col_cov = df[acols['column']].notna().mean() * 100
    high_cov_cols = (col_cov >= 90).sum()
    medium_cov_cols = ((col_cov >= 50) & (col_cov < 90)).sum()
    low_cov_cols = (col_cov < 50).sum()

    with_coords = df[['Latitude_decimal', 'Longitude_decimal']].dropna().shape[0]

    lines = [
        '# CMiO local inspection',
        '',
        '## Source',
        '- USGS — Tharalson, Graham, Emsbo, Magnin, 2025.',
        '  *Domestic and international rock geochemistry of ore and host rocks generated by the Critical Minerals Mapping Initiative.*',
        '- DOI: [10.5066/P14WGQ8V](https://doi.org/10.5066/P14WGQ8V)',
        '- ScienceBase item: [686ecb93d4be020e5c0a6c07](https://www.sciencebase.gov/catalog/item/686ecb93d4be020e5c0a6c07)',
        '- Companion publication: Case et al., 2025, USGS Fact Sheet 2025-3002 ([10.3133/fs20253002](https://doi.org/10.3133/fs20253002))',
        '',
        '## Files downloaded',
        '',
        '| File | Size | Purpose |',
        '| --- | --- | --- |',
        '| `250827_CMMI_Rock_Geochemistry_Data.csv` | 915 KB | sample × column geochemistry table |',
        '| `250827_CMMI_Rock_Geochemistry_DataDictionary.csv` | 136 KB | column definitions, units, detection ranges |',
        '| `250827_CMMI_Rock_Geochemistry_Metadata.xml` | 252 KB | FGDC CSDGM metadata |',
        '| `250827_CMMI_Rock_Geochemistry_Locations.png` | 396 KB | publisher-supplied sample map |',
        '',
        '## Table shape',
        f'- **{len(df):,} samples × {len(df.columns):,} columns**',
        f'- {len(META_COLS)} metadata columns + {n_analytical_total} analytical columns '
        f'({n_analytical_parsed} follow the `<Element>_<unit>_<method>` pattern; {len(unparsed)} do not — '
        f'{", ".join(f"`{c}`" for c in unparsed) or "none"})',
        f'- {len(unique_elements)} unique element/species symbols × {len(methods)} analytical methods',
        f'- Analytical-method columns with ≥ 90% coverage: **{high_cov_cols}**; 50–90%: {medium_cov_cols}; < 50%: {low_cov_cols}',
        f'- Samples with lat/lon coordinates: **{with_coords:,} / {len(df):,}**',
        '',
        '## Analytical-method suffixes observed',
        f'{", ".join(f"`{m}`" for m in methods)}',
        '',
        '## Deposit environments (top-level label)',
        '',
        '| Deposit_Environment | samples |',
        '| --- | ---: |',
    ]
    for env, n in envs.items():
        label = 'NaN / blank' if (pd.isna(env) or env == '' or env == ' ') else str(env)
        lines.append(f'| {label} | {int(n):,} |')

    lines += [
        '',
        '## Deposit groups',
        '',
        '| Deposit_Group | samples |',
        '| --- | ---: |',
    ]
    for grp, n in groups.items():
        label = 'NaN' if pd.isna(grp) else str(grp)
        lines.append(f'| {label} | {int(n):,} |')

    lines += [
        '',
        '## Top 15 deposit types',
        '',
        '| Deposit_Type | samples |',
        '| --- | ---: |',
    ]
    for typ, n in types.head(15).items():
        label = 'NaN' if pd.isna(typ) else str(typ)
        lines.append(f'| {label} | {int(n):,} |')

    lines += [
        '',
        '## Top 10 countries',
        '',
        '| Country | samples |',
        '| --- | ---: |',
    ]
    for c, n in countries.head(10).items():
        label = 'NaN' if pd.isna(c) else str(c)
        lines.append(f'| {label} | {int(n):,} |')

    lines += [
        '',
        '## Rock_Type',
        '',
        '| Rock_Type | samples |',
        '| --- | ---: |',
    ]
    for r, n in rocks.items():
        label = 'NaN' if pd.isna(r) else str(r)
        lines.append(f'| {label} | {int(n):,} |')

    lines += [
        '',
        '## Detection-limit convention',
        '',
        'From the data dictionary: values below the Lower Detection Limit (LDL) are encoded as the negated LDL',
        '(e.g. `-0.01` for an Ag column with LDL=0.01 ppm). For overflow past the Upper Detection Limit the value',
        '`X.1111` (e.g. `50000.1111`) is used. A blank means the sample was not analyzed for that method.',
        'When computing distributions in these previews, non-positive values are reported as "below LDL" and',
        'excluded from log-scale histograms.',
        '',
        '## Figures',
        '',
        '- `deposit_environment_counts.png` — 7-class deposit-environment histogram',
        '- `deposit_group_counts.png` — deposit-group histogram',
        '- `deposit_type_top.png` — top 20 deposit types',
        '- `country_counts.png` — top 15 countries',
        '- `rock_type_counts.png` — broad rock classification',
        '- `method_coverage.png` — per-column non-null fraction (sorted)',
        '- `element_coverage_heatmap.png` — element × deposit-environment coverage matrix',
        '- `element_distributions.png` — log-scale histograms for Au/Ag/Cu/Pb/Zn/Mo',
        '- `detection_limit_shares.png` — detected vs below-LDL counts for key ore metals',
        '- `geographic_scatter.png` — sample lat/lon colored by deposit environment',
        '',
        '## Notes on CMiO for the foundation model',
        '',
        '- Tabular, **deposit-type-labeled geochemistry** — complements CMMI (continental raster evidential',
        '  layers) and SeisDARE (local seismic sensing). This is the ore-system / compositional branch of the',
        '  three-layer dataset stack.',
        '- Strong label signal: every sample has `Deposit_Environment` plus deposit group/type derived from',
        '  the Hofstra et al. (2021) CMMI classification scheme.',
        '- Wide column dimensionality (292 analytical columns) but very **sparse** — multiple ICP packages',
        '  cover overlapping element sets, so most cells are null. Expect to work with element-aggregated',
        '  features (one "best" column per element) rather than all 292 raw columns.',
        '- Coordinate coverage is good for a global-scope release; most of the USA is densely sampled while',
        '  international sites (Sweden, Japan, Mexico, Australia, Spain, Austria) are sparser.',
        '- License: public domain (USGS data release).',
    ]
    out.write_text('\n'.join(lines), encoding='utf-8')


# ── Main ──────────────────────────────────────────────────────────────────
def main() -> None:
    if not DATA_CSV.exists():
        print(f'No Data.csv found at {DATA_CSV}')
        return

    print(f'Loading {DATA_CSV.relative_to(ROOT)} ...')
    df = pd.read_csv(DATA_CSV, low_memory=False)
    print(f'  shape = {df.shape}')

    acols = analytical_columns(df)
    print(f'  {len(acols)} analytical columns, {acols["element"].nunique()} unique elements')

    # Categoricals
    bar_counts(df['Deposit_Environment'].fillna('(missing)').value_counts(),
               f'Deposit_Environment (n={len(df):,})',
               OUT / 'deposit_environment_counts.png', rotation=25)
    bar_counts(df['Deposit_Group'].fillna('(missing)').value_counts(),
               f'Deposit_Group (n={len(df):,})',
               OUT / 'deposit_group_counts.png', rotation=35)
    bar_counts(df['Deposit_Type'].fillna('(missing)').value_counts().head(20),
               f'Top-20 Deposit_Type (n={len(df):,})',
               OUT / 'deposit_type_top.png', rotation=35, figsize=(12, 6))
    bar_counts(df['Country'].fillna('(missing)').value_counts().head(15),
               f'Top-15 countries (n={len(df):,})',
               OUT / 'country_counts.png', rotation=30)
    bar_counts(df['Rock_Type'].fillna('(missing)').value_counts(),
               f'Rock_Type (n={len(df):,})',
               OUT / 'rock_type_counts.png', rotation=20, color='tan')

    # Analytical structure
    plot_method_coverage(df, acols, OUT / 'method_coverage.png')
    plot_element_coverage_heatmap(df, acols, OUT / 'element_coverage_heatmap.png')
    plot_element_distributions(df, acols, OUT / 'element_distributions.png')
    plot_detection_limit_shares(df, acols, OUT / 'detection_limit_shares.png')
    plot_geographic_scatter(df, OUT / 'geographic_scatter.png')

    write_readme(df, acols, OUT / 'README.md')
    print(f'Saved previews + README to {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
